drop table colis if exists;
create table colis (id varchar(255), etat varchar(255), name varchar(255),  send_date DATE,recieve_date DATE, id_client varchar(255),  primary key (id));
drop table message if exists;
create table message (id varchar(255) ,status varchar(255))
drop table client if exists;
create table client (id bigint generated by default as identity (start with 1) ,name varchar(255),adress varchar(255))
drop table analyze if exists;
create table analyze (id bigint generated by default as identity (start with 1),start_date DATETIME , end_date DATETIME ,  primary key (id))